export const STUDENT = {
  personalInformation: {
    firstName: "",
    lastName: "",
    preferredName: "",
    address: "",
    city: "",
    state: "",
    zipcode: "",
    county: "",
    phone: "",
    cellphone: "",
    email: "",
    dataOfBirth: undefined,
    gender: undefined,
    hispanic: 3,
    hispanicSpecify: "",
    race: undefined,
    relationshipStatus: undefined,
    intakeDate: undefined,
    referralDate: undefined,
    referredBy: "",
  },
  immediateNeeds: {
    familyMembersNeedHelp: undefined,
    comments: undefined,
  },
  otherProviders: {
    whatOtherAgencies: undefined,
    whatServicesDo: undefined,
    areYouWorkingWith: undefined,
    qwhere: undefined,
    withWhom: undefined,
    areTheseServices: 3,
    comments: undefined,
  },
  englishFluency: {
    question_1: undefined,
    question_2: undefined,
    question_3: undefined,
    question_4: undefined,
    comments: undefined,
  },
  housing: {
    question_1: undefined,
    question_2: undefined,
    question_3: undefined,
    question_4: undefined,
    question_5: undefined,
    comments: undefined,
  },
  collateralNeeds: {
    question_1: undefined,
  },
  income: {
    question_1: undefined,
    question_2: undefined,
    question_3: undefined,
    question_4: undefined,
  },
};
